version: '3.8'

services:
  flowventory-app:
    build: .
    environment:
      - NODE_ENV=production
    networks:
      - flowventory-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flowventory-app
    networks:
      - flowventory-network

networks:
  flowventory-network:
    driver: bridge